import type { ThemeManifest } from './types'

export const EKOMART_MANIFEST: ThemeManifest = {
  key: 'ekomart',
  name: 'Ekomart',
  description: 'Grocery store — dense, Bootstrap-based, sidebar categories',
  thumbnail: '/img/themes/ekomart.png',
  tokens: {
    primary: '#2B8A3E',
    primaryForeground: '#ffffff',
    secondary: '#E67E22',
    secondaryForeground: '#ffffff',
    accent: '#F39C12',
    accentForeground: '#000000',
    background: '#F8F9FA',
    foreground: '#212529',
    surface: '#ffffff',
    surfaceForeground: '#212529',
    muted: '#E9ECEF',
    mutedForeground: '#6C757D',
    border: '#DEE2E6',
    destructive: '#DC3545',
    success: '#28A745',
    warning: '#FFC107',
    fontFamily: "'Inter', sans-serif",
    fontHeading: "'Inter', sans-serif",
    borderRadius: '0.375rem',
    headerVariant: 'mega',
    footerVariant: 'standard',
    containerMax: '1400px',
    cssFramework: 'tailwind',
  },
  defaultBlocks: {
    home: [
      {
        _id: "grostore-hero",
        _type: "Hero",
        _parent: null,
        title: "Bienvenido a Grostore",
        subtitle: "Productos frescos y de calidad directo a tu hogar",
        ctaLabel: "Comprar ahora",
        ctaHref: "/catalogo",
        styles: { background: "linear-gradient(135deg, #00A859, #007A3D)", color: "#ffffff" },
        height: 420,
      },
      {
        _id: "grostore-features",
        _type: "Benefits",
        _parent: null,
        items: [
          { icon: "Truck", title: "Envío gratis", description: "En compras +₲100.000" },
          { icon: "Shield", title: "Compra segura", description: "Pago 100% protegido" },
          { icon: "Clock", title: "Entrega rápida", description: "En 24-48 horas" },
          { icon: "Headphones", title: "Soporte 24/7", description: "Estamos para ayudarte" },
        ],
        styles: { padding: "3rem 0" },
      },
    ],
  },
}

export const ANVOGUE_MANIFEST: ThemeManifest = {
  key: 'anvogue',
  name: 'Anvogue',
  description: 'Fashion/multipurpose — minimal, clean, lots of whitespace',
  thumbnail: '/img/themes/anvogue.png',
  tokens: {
    primary: '#1A1A2E',
    primaryForeground: '#ffffff',
    secondary: '#E94560',
    secondaryForeground: '#ffffff',
    accent: '#0F3460',
    accentForeground: '#ffffff',
    background: '#ffffff',
    foreground: '#1A1A2E',
    surface: '#F8F9FA',
    surfaceForeground: '#1A1A2E',
    muted: '#F1F3F5',
    mutedForeground: '#868E96',
    border: '#E9ECEF',
    destructive: '#E94560',
    success: '#40C057',
    warning: '#FAB005',
    fontFamily: "'Inter', sans-serif",
    fontHeading: "'Playfair Display', serif",
    borderRadius: '0.5rem',
    headerVariant: 'classic',
    footerVariant: 'dark',
    containerMax: '1280px',
    cssFramework: 'tailwind',
  },
  defaultBlocks: {},
}

export const GROSTORE_MANIFEST: ThemeManifest = {
  key: 'grostore',
  name: 'Grostore',
  description: 'Grocery store — clean, modern, white+green, decorative shapes',
  thumbnail: '/img/themes/grostore.png',
  tokens: {
    primary: '#00A859',
    primaryForeground: '#ffffff',
    secondary: '#FF6B35',
    secondaryForeground: '#ffffff',
    accent: '#FFD700',
    accentForeground: '#000000',
    background: '#ffffff',
    foreground: '#1A1A1A',
    surface: '#F7F7F7',
    surfaceForeground: '#1A1A1A',
    muted: '#F0F0F0',
    mutedForeground: '#717171',
    border: '#E5E5E5',
    destructive: '#EF4444',
    success: '#22C55E',
    warning: '#F59E0B',
    fontFamily: "'DM Sans', sans-serif",
    fontHeading: "'DM Sans', sans-serif",
    borderRadius: '1rem',
    headerVariant: 'modern',
    footerVariant: 'newsletter',
    containerMax: '1320px',
    cssFramework: 'tailwind',
  },
  defaultBlocks: {},
}

export const BASE_MANIFEST: ThemeManifest = {
  key: 'base',
  name: 'Farmatotal',
  description: 'Pharmacy — default theme, fully configurable via ChaiBuilder',
  thumbnail: '/img/themes/base.png',
  tokens: {
    primary: '#E8590C',
    primaryForeground: '#ffffff',
    secondary: '#2B8A3E',
    secondaryForeground: '#ffffff',
    accent: '#F59F00',
    accentForeground: '#000000',
    background: '#ffffff',
    foreground: '#1A1B1E',
    surface: '#F8F9FA',
    surfaceForeground: '#1A1B1E',
    muted: '#F1F3F5',
    mutedForeground: '#868E96',
    border: '#DEE2E6',
    destructive: '#E03131',
    success: '#2F9E44',
    warning: '#F08C00',
    fontFamily: "'Inter', sans-serif",
    fontHeading: "'Inter', sans-serif",
    borderRadius: '0.5rem',
    headerVariant: 'mega',
    footerVariant: 'standard',
    containerMax: '1400px',
    cssFramework: 'tailwind',
  },
  defaultBlocks: {},
}

export const THEMES_MANIFEST: Record<string, ThemeManifest> = {
  base: BASE_MANIFEST,
  ekomart: EKOMART_MANIFEST,
  anvogue: ANVOGUE_MANIFEST,
  grostore: GROSTORE_MANIFEST,
}

export function getThemeManifest(key: string): ThemeManifest {
  return THEMES_MANIFEST[key] ?? BASE_MANIFEST
}
